# Custom Language File for Launcher Customizer

[ejs.app]
title = "CP Launcher"

[ejs.landing]
mediaHomeURL = "#"
mediaLinkURL = "#"
mediaMapURL = "#"
mediaGitHubURL = "https://github.com/githubmahan/CPLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/HwcUG96gEB"

[ejs.settings]
sourceGithubLink = "https://github.com/githubmahan/CPLauncher"
supportLink = "https://discord.gg/HwcUG96gEB"

[ejs.welcome]
welcomeHeader = "CP Launcher"
welcomeDescription = "철팽모드서버에 필요한 모드와 편의성 모드를 곁들인 런처입니다."
welcomeDescCTA = "철팽모드서버 전용 런처입니다."
